# Deployment configuration

repo-name    = "Foundation-security-services-setup"
part-of      = 'foundation'


[[Script]]
name         = 'setup-security-services'
args         = [['--aws-config', '{AWSConfigEnabled}'],
                ['--guardduty', '{GuardDutyEnabled}'],
                ['--security-hub', '{SecurityHubEnabled}'],
                ['--access-analyzer', '{IAMAccessAnalyzerEnabled}'],
                ['--detective', '{DetectiveEnabled}'],
                ['--inspector', '{InspectorEnabled}'],
                ['--accounts', '../Installer/apps/accounts.toml']]

            