# Deployment configuration

repo-name    = "Foundation-security-services-setup"
part-of      = 'foundation'


[[Script]]
name         = 'setup-security-services'
args         = [['--aws-config', '{AWSConfigEnabled}'],
                ['--guardduty', '{GuardDutyEnabled}'],
                ['--security-hub', '{SecurityHubEnabled}'],
                ['--access-analyzer', '{IAMAccessAnalyzerEnabled}'],
                ['--detective', '{DetectiveEnabled}'],
                ['--inspector', '{InspectorEnabled}'],
                ['--admin-account', '{admin-account}'],
                ['--security-account', '{security-account}'],
                ['--regions', '{all-regions}'],
                ['--cross-account-role', '{cross-account-role}'],
                ['--org-id', '{org-id}'],
                ['--root-ou', '{root-ou}']]

            